Some propositions to improve the CMake compilation
jeffhammond/BigMPI pull request #41
Opened 2020-07-02 12:17 UTC by Algiane

Hello,

I am interested to use the BigMPI wrappers in one of my project. For this, I want to import BigMPI as a CMake external project and I have made some modifications in my fork that you may be interested to merge.
I have added/modified: 
 - The library installation (you can set the `CMAKE_INSTALL_PREFIX` variable to modify the default location);
  - the setting of the `MACOSX_RPATH` variable;
  - the project definition (and the setting of BigMPI as subproject if needed);
  - the using of the `set_property` functionnality to set the `-std=c99` flag in a more portable way;
  - the linking with mpi library (I think that it avoids the needed to set `CMAKE_C_COMPILER` to `mpicc` but I am not sure);
  - the renaming of the 'test' target as the 'bigmpi_test' one to avoid cmake complains (so tests are lauching by the `make bigmpi_test` command): the test target is already used by CMake for tests created with the `CTest` command.

I have tried to stay close to your previous CMakeLists files so I hope that it will suit you.

Regards,

Algiane

2020-07-02 17:22 UTC, jeffhammond commented
@gentryx Can you please review this?  I recall you wrote the CMake stuff.  If you don't have time, I will find somebody to help since I have a well-known aversion to CMake ;-)

2020-07-02 17:25 UTC, jeffhammond commented
@Algiane Thanks for your interest and willingness to contribute.  Because I don't use BigMPI in production and because I use the Autotools buildsystem, I will be happy to merge whatever CMake changes work for you as a downstream user.  A willingness to use and contribute to BigMPI earns you a rather significant voting share in the development of the project :-)

2020-07-03 14:39 UTC, gentryx requested changes
All in all LGTM, just one nit about the loop variable (see above).

2020-07-03 14:39 UTC, gentryx commented on test/CMakeLists.txt
> -foreach(test ${TESTS})
I don't think the variable name here needs to change. Could you revert this change?

2020-07-06 07:40 UTC, Algiane commented
Hi @gentryx,

Thank you for the reviewing: you are right, this modification was useless.
It is reverted now.

Best,
Algiane

2020-07-06 11:19 UTC, gentryx approved these changes
Thanks a ton Algiane!

2020-07-06 11:19 UTC, merged

2020-07-06 23:57 UTC, jeffhammond commented
It's not related to this pull request but you both might be interested to know that large count support is on track for MPI 4.0.  See BigCount on https://www.mpi-forum.org/meetings/2020/06/votes.

2020-07-07 07:19 UTC, Algiane commented
Thank you for the information: it is a very good news!
Have a nice day.

Algiane